[project]
name = "home-portal-backend"
version = "0.1.0"
description = "Backend API for Home-Portal, a portal for daily personal QOL improvement."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argon2-cffi>=25.1.0",
    "django>=6.0.2",
    "django-cors-headers>=4.9.0",
    "django-filter>=25.2",
    "django-stubs>=5.2.9",
    "djangorestframework>=3.16.1",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.29.0",
    "gunicorn>=25.1.0",
    "pre-commit>=4.5.1",
    "psycopg2-binary>=2.9.11",
    "pynvim>=0.6.0",
    "python-dotenv>=1.2.1",
    "ruff>=0.15.4",
]

[tool.ruff]
exclude = ["**/migrations/**", "manage.py"]
